version: '3.8'

services:
  rdf-store:
    build:
      context: ./graphdb
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g

  webui:
    build:
      context: ./management_webpage
    ports:
      - 5000:5000
    volumes:
      - ./ui_config.json:/app/config.json
