version: '3.8'

services:
  rdf-store:
    build:
      context: ./graphdb
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g

  webui:
    build:
      context: ./management_webpage
    ports:
      - 5000:5000
    volumes:
      - ./ui_config.json:/app/config.json
  
  triplifier:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier-boot:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - TASK_WORKDIR=/triplifier-workdir
      - TASK_SPARQLURL=http://rdf-store:7200
    volumes:
      - triplifier_workdir:/triplifier-workdir

volumes:
  triplifier_workdir: