version: '3.8'

services:
  rdf-store:
    image: ghcr.io/maastrichtu-cds/fair_tools_docker-graphdb/docker-graphdb:latest
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g
    volumes:
      - rdf_storage_dir:/opt/graphdb/home/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/repositories"]
      interval: 5s
      timeout: 3s
      retries: 5

  webui:
    image: ghcr.io/maastrichtu-cds/epnd-fairification:main
    ports:
      - 5000:5000
    environment:
      - GRAPHDB_SERVER=http://rdf-store:7200
      - REPOSITORY=epnd_dummy
      - RDF_ENDPOINT=http://rdf-store:7200/repositories/epnd_dummy
      - TRIPLIFIER_SERVICE=http://localhost:8080
    depends_on:
      rdf-store:
        condition: service_healthy

  triplifier:
    image: ghcr.io/maastrichtu-cds/triplifier-boot:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - TASK_WORKDIR=/triplifier-workdir
      - TASK_SPARQLURL=http://rdf-store:7200
    volumes:
      - triplifier_workdir:/triplifier-workdir

volumes:
  rdf_storage_dir:
  triplifier_workdir:
