version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./demo_HEAD-NECK/INFOclinical_HN_Version2_30may2018_concat.sql:/docker-entrypoint-initdb.d/INFOclinical_HN_Version2_30may2018_concat.sql
      - ./demo_HN1/HN1_Clinical_data_updated_July_2020.sql:/docker-entrypoint-initdb.d/HN1_Clinical_data_updated_July_2020.sql
      - ./demo_HNSCC/HNSCC_Clinical_Data.sql:/docker-entrypoint-initdb.d/HNSCC_Clinical_Data.sql
      - ./demo_OPC/Clinical_data_list_OPC_v3.sql:/docker-entrypoint-initdb.d/Clinical_data_list_OPC_v3.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: root

  rdf-store:
    build:
      context: ./graphdb
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g

  triplifier_head_neck:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier:1.1.0
    hostname: head_neck.local
    # environment:
      # - SLEEPTIME=360
    volumes:
      - ./data_descriptor/triplifier_head_neck.properties:/triplifier.properties
    healthcheck:
      test: ["CMD", "exited with code 0"]
  triplifier_hn_one:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier:1.1.0
    hostname: hn_one.local
    # environment:
      # - SLEEPTIME=360
    volumes:
      - ./data_descriptor/triplifier_hn_one.properties:/triplifier.properties
    healthcheck:
      test: ["CMD", "exited with code 0"]
  triplifier_hnscc:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier:1.1.0
    hostname: hnscc.local
    # environment:
    #   - SLEEPTIME=360
    volumes:
      - ./data_descriptor/triplifier_hnscc.properties:/triplifier.properties
    healthcheck:
      test: ["CMD", "exited with code 0"]  
  triplifier_opc:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier:1.1.0
    hostname: opc.local
    # environment:
    #   - SLEEPTIME=360
    volumes:
      - ./data_descriptor/triplifier_opc.properties:/triplifier.properties
    healthcheck:
      test: ["CMD", "exited with code 0"]

  annotations:
    depends_on: 
        triplifier_hn_one:
          condition: service_healthy
        triplifier_head_neck:
          condition: service_healthy
        triplifier_hnscc:
          condition: service_healthy
        triplifier_opc:
          condition: service_healthy
    build: ./annotations
    container_name: annotations

  dashoard:
    build: ./annotations/demo_dash
    ports:
      - "8050:8050"
    container_name: dashboard