services:
  web:
    container_name: fairnotator
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/static
    command: gunicorn fairnotator.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: fairnotator_db
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8080:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: