# Retrieve all mappings in the current database (named graph http://mapping.local/)

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?columnUri ?targetUri
WHERE {
    GRAPH <http://mapping.local/> {
        ?columnUri owl:equivalentClass ?targetUri
    }
}
