PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?colUri ?columnName ?tableName 
where { 
	?colUri rdfs:subClassOf dbo:ColumnCell;
         dbo:column ?columnName;
         dbo:table ?tableUri.
   	?tableUri dbo:table ?tableName.
}
