version: '3.9'

services:

  annotations:
    build: ./
    container_name: annotations
    networks:
      - my-proxy-net

  dashoard:
    build: ./demo_dash
    ports:
      - "8050:8050"
    container_name: dashboard
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network