apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rdf-store
  name: rdf-store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rdf-store
  strategy:
    type: Recreate
  securityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rdf-store
    spec:
      serviceAccountName: anyuid
      containers:
        - env:
            - name: GDB_HEAP_SIZE
              value: 2g
            - name: GDB_MAX_MEM
              value: 2g
            - name: GDB_MIN_MEM
              value: 1g
          image: ghcr.io/maastrichtu-cds/fair_tools_docker-graphdb/docker-graphdb:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://rdf-store-epnd.apps.dsri2.unimaas.nl/repositories
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 3
          name: rdf-store
          ports:
            - containerPort: 7200
          resources: {}
          volumeMounts:
            - mountPath: /opt/graphdb/home/data
              name: rdf-storage
      restartPolicy: Always
      volumes:
        - name: rdf-storage
          persistentVolumeClaim:
            claimName: rdf-storage
status: {}
