apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webui
    spec:
      serviceAccountName: anyuid
      securityContext:
        seLinuxOptions:
          level: 's0:c67,c49'
        runAsUser: 0
        supplementalGroups:
          - 100
      containers:
        - env:
            - name: GRAPHDB_SERVER
              value: http://rdf-store:7200
            - name: RDF_ENDPOINT
              value: http://rdf-store:7200/repositories/epnd_dummy
            - name: REPOSITORY
              value: epnd_dummy
            - name: TRIPLIFIER_SERVICE
              value: http://localhost:8080
          image: ghcr.io/maastrichtu-cds/epnd-fairification:main
          name: webui
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
