apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webui
    spec:
      serviceAccountName: anyuid
      containers:
        - env:
            - name: GRAPHDB_SERVER
              value: http://rdf-store-epnd.apps.dsri2.unimaas.nl
            - name: RDF_ENDPOINT
              value: http://rdf-store-epnd.apps.dsri2.unimaas.nl/repositories/epnd_dummy
            - name: REPOSITORY
              value: epnd_dummy
            - name: TRIPLIFIER_SERVICE
              value: http://triplifier-epnd.apps.dsri2.unimaas.nl
          image: ghcr.io/maastrichtu-cds/epnd-fairification:dev
          name: webui
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
