prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sio: <http://semanticscience.org/resource/>

SELECT ?nodeShape ?variableUri ?variableType ?variableTypeLabel
WHERE {
    ?nodeShape rdf:type sh:NodeShape;
        sh:targetClass ?variableUri.
    
    OPTIONAL {
        ?nodeShape rdf:type ?variableType.
        ?variableType rdfs:label ?variableTypeLabel.
        FILTER (?variableType IN (sio:SIO_000137, sio:SIO_000915)).
    }
    
    ## Better option would be to say that variableUri should not be something from Unit ontology
    ## but this works for now
    MINUS {
        ?nodeShape sh:property [
            sh:path sio:SIO_000300;
        ];
    }
}