version: '3.8'
services:
  rdf-store:
    image: registry.gitlab.com/um-cds/fair/tools/docker-graphdb:latest
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g
  triplifier:
    image: registry.gitlab.com/um-cds/fair/tools/triplifier-boot:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - TASK_WORKDIR=/triplifier-workdir
      - TASK_PROPERTIES_FILE=/config/triplifier.properties
    volumes:
      - ./triplifier-workdir:/triplifier-workdir