############################################################
# execution command: `oc apply -f kubernetes.yaml`
############################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairnotator-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fairnotator-single
  template:
    metadata:
      labels:
        app: fairnotator-single
    spec:
      serviceAccountName: anyuid
      securityContext:
        seLinuxOptions:
          level: 's0:c45,c20'
        runAsUser: 0
        supplementalGroups:
          - 100
      containers:
        - name: fairnotator-single
          image: jvsoest/adwb-30012023
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            - containerPort: 8080
            - containerPort: 7200
          env:
            - name: TRIPLIFIER_LOCATION
              value: "http://fairnotator-single-triplifier-epnd.apps.dsri2.unimaas.nl"
          securityContext:
            capabilities:
              drop:
                - MKNOD
---
kind: Service
apiVersion: v1
metadata:
  name: fairnotator-single
spec:
  selector:
    app: fairnotator-single
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: fairnotator-triplifier
    - port: 5000
      targetPort: 5000
      name: fairnotator-ui
    - port: 7200
      targetPort: 7200
      name: fairnotator-graphdb
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fairnotator-single-ui
  namespace: epnd
  labels: {}
spec:
  to:
    kind: Service
    name: fairnotator-single
  tls: null
  port:
    targetPort: fairnotator-ui
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fairnotator-single-graphdb
  namespace: epnd
  labels: {}
spec:
  to:
    kind: Service
    name: fairnotator-single
  tls: null
  port:
    targetPort: fairnotator-graphdb
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fairnotator-single-triplifier
  namespace: epnd
  labels: {}
spec:
  to:
    kind: Service
    name: fairnotator-single
  tls: null
  port:
    targetPort: fairnotator-triplifier