name: Build WebUI

on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  containerize:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./management_webpage
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}
      - name: Retag to latest
        uses: koraykoska/retag-docker-image@0.2.4
        if: steps.extract_branch.outputs.branch == 'main'
        with:
          registry: ${{ env.REGISTRY }}
          name: ghcr.io/${{ env.REPO }}
          old_tag: ${{ steps.extract_branch.outputs.branch }}
          new_tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
